#Export the raw public metadata for all stories returned by the query. 
parameters:
    QUERY:
        type: str
    COLLECTIONS:
        type: List[str] 
    SOURCES:
        type: List[str]
    START_DATE:
        type: date
    END_DATE:
        type: date
    NAME:
        type: str
        
steps:
    #Discovery Block
    - QueryOnlineNews:
        params:
            api_key_block: 'mediacloud-api-key'
            query: $QUERY
            collections: $COLLECTIONS
            sources: $SOURCES
            start_date: $START_DATE
            end_date: $END_DATE
        outputs:
            text: text
            title: article_title
            media_name: domain
            publish_date: pub_date
            url: url
            language: language

    - CSVToS3:
        params:
            restricted: False
            task_name: "metadata-export"
            columns:
                - article_title
                - domain
                - pub_date
                - url
                - language
            credentials_block: "aws-s3-credentials"
            bucket_name: "mediacloud-sous-chef-output"
            object_name: "sc-kitchen/DATE/$NAME-metadata.csv"
            object_date_slug: true

    - CSVToS3:
        params:
            restricted: true
            task_name: "full-text-metadata-export"
            columns:
                - text
                - article_title
                - domain
                - pub_date
                - url
                - language
            credentials_block: "aws-s3-credentials"
            bucket_name: "mediacloud-sous-chef-output"
            object_name: "sc-kitchen/DATE/$NAME-full-metadata.csv"
            object_date_slug: true