# NOTE! This file expects to be run by deploy.sh
#	which passes environment variables to be interpolated!!

version: "3.8"

services:
  # MUST match PREFECT_CONTAINER_NAME in swarm .yml file:
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - target: $PREFECT_PORT
        published: $PREFECT_PORT_PUBLISHED
        protocol: tcp
        mode: ingress
    environment:
      PREFECT_HOME: /data
    deploy:
      replicas: $PREFECT_CONTAINERS
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  prefect-config:
    image: $KITCHEN_IMAGE
    entrypoint: ["python", "/app/prefect-config.py"]
    environment:
      PREFECT_API_URL: $PREFECT_URL
      WORK_POOL_NAME: $PREFECT_WORK_POOL_NAME
    env_file:
      - $PRIVATE_CONF_FILE
    deploy:
      restart_policy:
        condition: none  # Run once
    networks:
      - my-network

  prefect-worker:
    image: prefecthq/prefect:3-latest
    command: prefect worker start --pool $PREFECT_WORK_POOL_NAME
    environment:
      PREFECT_API_URL: $PREFECT_URL
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  kitchen-api:
    image: $KITCHEN_IMAGE
    command: uvicorn sous_chef_kitchen.kitchen.api:app --host 0.0.0.0 --port $KITCHEN_PORT --reload
    ports:
      - target: $KITCHEN_PORT
        published: $KITCHEN_PORT_PUBLISHED
        protocol: tcp
        mode: ingress
    environment:
      PREFECT_API_URL: $PREFECT_URL
      SC_PREFECT_DEPLOYMENT: kitchen-base
      SC_PREFECT_WORK_POOL: $PREFECT_WORK_POOL_NAME
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

networks:
  my-network:
    driver: overlay
    name: $NETWORK_NAME
