#Export the top 100 entities found in the content returned by the query
parameters:
    QUERY:
        type: str
    COLLECTIONS:
        type: List[str] 
    START_DATE:
        type: date
    END_DATE:
        type: date
    NAME:
        type: str
        
steps:
    #Discovery Block
    - QueryOnlineNews:
        params:
            api_key_block: 'mediacloud-api-key'
            query: $QUERY
            collections: $COLLECTIONS
            start_date: $START_DATE
            end_date: $END_DATE
        outputs:
            text: text
            title: article_title
            media_name: domain
            publish_date: pub_date
            url: url
            language: language

    - SpacyNER:
        inputs:
            text: text
        outputs:
            entities: entities

    - TopNEntities:
        params:
            top_n: 100
            sort_by: "percentage"
        inputs:
            entities: entities
        outputs:
            top_entities: top_entities
            entity_counts: entity_counts
            entity_appearance_percent: entity_percent

    - CSVToS3:
        params:
            restricted: False
            task_name: "entities-export"
            columns:
                - top_entities
                - entity_counts
                - entity_percent
            credentials_block: "aws-s3-credentials"
            bucket_name: "mediacloud-sous-chef-output"
            object_name: "sc-kitchen/DATE/$NAME-entities.csv"
            object_date_slug: true


